name: CI

on: [push, pull_request]

jobs:
  test-core:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        haxe-version: [4.3.0]
        node-version: ['14']
        python-version: ['3.x']
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install vsce
      - uses: kiss-lang/setup-lix@main
        with:
          lix-version: 15.12.0
      - run: lix download
      - run: ./test.sh
        shell: bash
      
